apiVersion: v1
data:
  alertmanager.yaml: Z2xvYmFsOgogIHJlc29sdmVfdGltZW91dDogNW0KICB3ZWNoYXRfYXBpX2NvcnBfaWQ6ICcxMDAwMDAyJwogIHdlY2hhdF9hcGlfdXJsOiAnaHR0cHM6Ly9xeWFwaS53ZWl4aW4ucXEuY29tL2NnaS1iaW4vJwogIHdlY2hhdF9hcGlfc2VjcmV0OiAnd3ViOTNpXzd3ekFZUUJVVFhpajBic2owOHg3V3p5a1pWT2RHeFJZRkU2YycKcm91dGU6CiAgcmVjZWl2ZXI6ICd3ZWNoYXQnCiAgZ3JvdXBfYnk6IFsnYWxlcnRuYW1lJ10KICBncm91cF93YWl0OiAgICAgIDMwcwogIGdyb3VwX2ludGVydmFsOiAgM20KICByZXBlYXRfaW50ZXJ2YWw6IDNtCnJlY2VpdmVyczoKLSBuYW1lOiAnd2VjaGF0JwogIHdlY2hhdF9jb25maWdzOgogIC0gc2VuZF9yZXNvbHZlZDogdHJ1ZQogICAgY29ycF9pZDogJ3d3NWFmMjg5MTRkZGY5NGIzYScKICAgIHRvX3BhcnR5OiAnMTQnCiAgICBhZ2VudF9pZDogJzEwMDAwMDInCiAgICBhcGlfc2VjcmV0OiAnd3ViOTNpXzd3ekFZUUJVVFhpajBic2owOHg3V3p5a1pWT2RHeFJZRkU2YycKICAgIG1lc3NhZ2U6ICJhbGVydCB7eyAuQ29tbW9uQW5ub3RhdGlvbnMuYWxlcnQgfX0gXG5zZXZlcml0eSAge3sgLkNvbW1vbkFubm90YXRpb25zLnNldmVyaXR5IH19IFxubWVzc2FnZToge3sgLkNvbW1vbkFubm90YXRpb25zLm1lc3NhZ2UgfX0iCg==
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
type: Opaque
