apiVersion: v1
kind: Endpoints
metadata:
  labels:
    k8s-app: etcd
  name: etcd
  namespace: kube-system
subsets:
- addresses:
  - ip: 10.15.4.253
  - ip: 10.15.4.254
  - ip: 10.15.4.255
  ports:
  - name: metrics
    port: 2379
    protocol: TCP
